# Generated by Django 3.0.6 on 2021-06-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='response',
            field=models.TextField(),
        ),
    ]
