# Generated by Django 3.0.6 on 2021-06-18 18:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_auto_20210619_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='response',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
