# Generated by Django 2.2.8 on 2021-06-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_alter_suggest_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
