# Generated by Django 2.2.8 on 2021-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_auto_20210619_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='intent',
            field=models.TextField(default=None),
        ),
    ]
